// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4yuMyAWvchl75WFDXqafYdyaI0w0EweM',
    appId: '1:321802860181:web:ba7f23897233cb250f8d9c',
    messagingSenderId: '321802860181',
    projectId: 'iotproject-f6abf',
    authDomain: 'iotproject-f6abf.firebaseapp.com',
    databaseURL: 'https://iotproject-f6abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-f6abf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgC5H9l70ELIzjZBjVS-mZ0_L_7E-ou4c',
    appId: '1:321802860181:android:7a5fac8f26dc45780f8d9c',
    messagingSenderId: '321802860181',
    projectId: 'iotproject-f6abf',
    databaseURL: 'https://iotproject-f6abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-f6abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-_0JmIzd3MSqY2hfzLyb09spcygJC-k',
    appId: '1:321802860181:ios:050da902b238b7150f8d9c',
    messagingSenderId: '321802860181',
    projectId: 'iotproject-f6abf',
    databaseURL: 'https://iotproject-f6abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-f6abf.appspot.com',
    iosBundleId: 'com.example.demoapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-_0JmIzd3MSqY2hfzLyb09spcygJC-k',
    appId: '1:321802860181:ios:050da902b238b7150f8d9c',
    messagingSenderId: '321802860181',
    projectId: 'iotproject-f6abf',
    databaseURL: 'https://iotproject-f6abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-f6abf.appspot.com',
    iosBundleId: 'com.example.demoapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4yuMyAWvchl75WFDXqafYdyaI0w0EweM',
    appId: '1:321802860181:web:98cdbb37be66de0b0f8d9c',
    messagingSenderId: '321802860181',
    projectId: 'iotproject-f6abf',
    authDomain: 'iotproject-f6abf.firebaseapp.com',
    databaseURL: 'https://iotproject-f6abf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-f6abf.appspot.com',
  );

}